apiVersion: apps/v1
kind: Deployment
metadata:
  name: cndoor-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cndoor
  template:
    metadata:
      labels:
        app: cndoor
    spec:
      containers:
        - name: cndoor
          image: krishnasanjayj/cndoor:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: cndoor-pvc
